### ISSUE TITLE
html中的亿些问题

### ISSUE THREAD

**Issue by DuckBurnIncense** [Lingxiiii/genshin#1]
https://github.com/Lingxiiii/genshin/blob/d54705b081309ad22942227cf029c7332cd06af5/index.html#L1
https://github.com/Lingxiiii/genshin/blob/d54705b081309ad22942227cf029c7332cd06af5/index.html#L8

- `<header>` 标签应为 `<head>`;
- html文档最开头应该有 `<!DOCTYPE html>` 和 `<html>`标签.

---

https://github.com/Lingxiiii/genshin/blob/d54705b081309ad22942227cf029c7332cd06af5/index.html#L2-L3

- `<meta charset="utf-8">` 应该紧接着 `<head>` 标签 (也就是 `<title>` 和 `<meta>` 标签位置应该互换).

---

https://github.com/Lingxiiii/genshin/blob/d54705b081309ad22942227cf029c7332cd06af5/index.html#L6

- `div` 后面不应有冒号;
- `text-align` 后的冒号为中文冒号, 应改为英文冒号;
- `red` 后遗漏了分号.

建议修改如下:

```css
div {
    text-align: center;
    color: red;
}
```

---

https://github.com/Lingxiiii/genshin/blob/d54705b081309ad22942227cf029c7332cd06af5/index.html#L11

- `<center>` 标签未闭合;
- HTML5 不支持 `<center>` 标签, 应使用 css 替代.

---

https://github.com/Lingxiiii/genshin/blob/d54705b081309ad22942227cf029c7332cd06af5/index.html#L13-L104

- 一堆 `<br>` 建议换为 `<p>` 标签.

---

综合建议修改如下:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>一叠刀</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>
		<style type="text/css">
			body {
				text-align: center;
				color: red
			}
		</style>
	</head>
	<body>
		“我果然，没在被神明注视着啊……”<br>
		<br>
		“坎瑞亚没有亡国，对吗？”<br>
		“直到今天，你们仍是我的荣耀。”<br>
		<br>
		“他死在了无风的烬寂海，风带不走他的灵魂……”<br>
		“故友的灵魂，可以交给我吗？”<br>
		<br>
		“摩拉克斯，若有缘，他日必将再会。”<br>
		<br>
		“总会有地上的生灵，敢于直面雷霆的威光。”<br>
		<br>
		“大哥！”<br>
		“浮舍大哥！”<br>
		“喂，浮舍！”<br>
		“浮舍…”<br>
		<br>
		“你生来就是这样的命！只要活着，就会给身边的人带来危险，还不如就这样死去，换她回来……”<br>
		<br>
		“孩童时期的梦是最易碎的东西。”<br>
		<br>
		“ 为什么先到坎瑞亚的不是 我……”<br>
		<br>
		“飞翔吧，飞翔吧，就像飞鸟那样，<br>
		代我看看这个世界，<br>
		代我飞到高天之上。”<br>
		<br>
		“我…我「花散里」，是「狐斋宫」大人的记忆，凝聚而成的污秽。”<br>
		<br>
		“「不被蒙蔽，不受动摇，一直走在你所坚信的道路上。」”<br>
		<br>
		“就像是我记得稻妻的一切一样，只要你记得我，我就能永远的活着。”<br>
		<br>
		“我知道神明无所不能，愿意将力量赐予人类，说明神对我们有深厚的期望。如今将军大人遭遇困境，更是我们实现诺言的时候。”<br>
		<br>
		“常道恢弘，鸣神永恒！”<br>
		<br>
		“有乐斋，我真的每天都过的很快乐哦。”<br>
		<br>
		“所以……卡卡塔一直收集零件，是因为它觉得这样能「修好」自己的主人？”<br>
		<br>
		“不用担心，森林会记住一切。”<br>
		<br>
		“没能看到妮露的花神之舞，果然还是有些遗憾呢。” <br>
		<br>
		你们既然能忍受我的苦寒，那<br>
		心中一定都有炽烈的欲望吧<br>
		<br>
		但是，我应该确确实实在这里等一<br>
		个人 等了三十年<br>
		<br>
		这是我对众生的信任，辜了整个世界的哀思负了它就是玷污我的血肉<br>
		<br>
		抱歉让你们和我一起背负<br>
		<br>
		他们的声音，常常在我耳边响起虽然她化作了神樱，但，这也是永恒<br>
		<br>
		替我燃烧旧世界吧<br>
		<br>
		少年自愿献祭，献出了自己的鲜血<br>
		<br>
		我上任的第一件事是爷爷的葬礼<br>
		<br>
		黎明到来之前总要<br>
		有人来照亮黑暗<br>
		<br>
		磐石，<br>
		也会归<br>
		于尘土<br>
		<br>
		爸爸妈妈什么时候才回来啊…<br>
		<br>
		派蒙最好<br>
		的伙伴<br>
		<br>
		三位死于非名，一位不知踪迹<br>
		<br>
		孩童时期的梦是最易碎的东西<br>
		<br>
		如果哪天我失控了．…可以期待你来阻止我吗<br>
		<br>
		花散里<br>
		<br>
		若你困于<br>
		无风之地<br>
		<br>
		枫叶红时<br>
		总多离别<br>
		<br>
		让世界...彻底遗忘我...<br>
		<br>
		我们终将重逢​
	</body>
</html>
```

(一堆 `<br>` 我是真的懒得改了)

(其实还有很多不规范的地方, 比如 `<html>` 标签没有 `lang` 属性等, 懒得改了)

**Comment by Lingxiiii** [comment]
已阅，后续更新中将修复部分问题

- [x] css错误引号
- [x] html头
- [ ] br=>p

**Comment by Lingxiiii** [comment]
-[x]br 替换为p（实际上是由div直接改成了p）

**Comment by Lingxiiii** [comment]
- [x] br已移除
